<a href="https://colab.research.google.com/github/prisilveira/Redi/blob/main/Introduction_to_Pandas_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Before Wednesday (20th September 2023): Check out the notebook (+ if you have time you can already start with the exercises)
- On Wednesday: Work on the exercises in the class
- Before Monday (25th September 2023): Finish the exercises and submit the solution

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
rentals = pd.read_csv("https://raw.githubusercontent.com/juliandnl/redi_ss20/master/berlin_rental.csv")

In [ ]:
rentals

          Region        Condition  Rooms     Rent  Year_Construction   Space
0          Mitte   first_time_use    4.0  2659.00               2019  117.20
1      Kreuzberg   first_time_use    1.0  1200.00               2020   29.33
2       Köpenick        well_kept    2.0   979.00               1997   83.61
3    Wilmersdorf        well_kept    4.0  1830.22               1900  171.18
4      Kreuzberg   first_time_use    2.0  2272.00               2020   88.27
..           ...              ...    ...      ...                ...     ...
759      Wedding   mint_condition    1.0   959.00               2017   27.80
760      Wedding   mint_condition    1.0   649.00               2017   20.50
761  Wilmersdorf   mint_condition    4.0  2750.00               2017  110.00
762     Köpenick        well_kept    2.0  1259.00               2017   91.20
763     Neukölln  fully_renovated    2.0   888.00               1990   68.48

[764 rows x 6 columns]

# Basic Dataframe structure

In [ ]:
# Get the first 10 rows in the Dataframe
rentals.head(10)

            Region       Condition  Rooms     Rent  Year_Construction   Space
0            Mitte  first_time_use    4.0  2659.00               2019  117.20
1        Kreuzberg  first_time_use    1.0  1200.00               2020   29.33
2         Köpenick       well_kept    2.0   979.00               1997   83.61
3      Wilmersdorf       well_kept    4.0  1830.22               1900  171.18
4        Kreuzberg  first_time_use    2.0  2272.00               2020   88.27
5         Köpenick       well_kept    2.0   840.00               1997   73.51
6            Mitte  mint_condition    2.0  1509.45               2015   61.61
7   Charlottenburg       well_kept    2.0   730.73               1900   72.61
8  Friedrichsfelde       well_kept    2.0   561.93               1971   62.40
9       Tiergarten  first_time_use    3.0  1789.00               2020   77.66

In [ ]:
# Get the last 10 rows in the Dataframe
rentals.tail(10)

          Region        Condition  Rooms    Rent  Year_Construction   Space
754        Mitte   no_information    3.0  2155.5               1879   86.42
755   Prenzlauer       modernized    1.0   577.0               1908   48.47
756      Wedding   mint_condition    1.0   772.0               2017   20.50
757   Tiergarten        well_kept    4.0  1970.0               1900  127.00
758     Neukölln       modernized    2.0   693.0               1905   57.00
759      Wedding   mint_condition    1.0   959.0               2017   27.80
760      Wedding   mint_condition    1.0   649.0               2017   20.50
761  Wilmersdorf   mint_condition    4.0  2750.0               2017  110.00
762     Köpenick        well_kept    2.0  1259.0               2017   91.20
763     Neukölln  fully_renovated    2.0   888.0               1990   68.48

In [ ]:
# Get the columns of the Dataframe
rentals.columns

Index(['Region', 'Condition', 'Rooms', 'Rent', 'Year_Construction', 'Space'], dtype='object')

In [ ]:
# Get the index of the Dataframe. What is the index and what are the columns of a Dataframe?
rentals.index

RangeIndex(start=0, stop=764, step=1)

In [ ]:
rentals.columns

Index(['Region', 'Condition', 'Rooms', 'Rent', 'Year_Construction', 'Space'], dtype='object')

In [ ]:
# Get the number of rows and number of columns in the Dataframe
rentals.shape

(764, 6)

In [ ]:
# What function can you use to quickly get an overview of the Dataframe?
rentals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Region             764 non-null    object
 1   Condition          764 non-null    object
 2   Rooms              764 non-null    float64
 3   Rent               764 non-null    float64
 4   Year_Construction  764 non-null    int64
 5   Space              764 non-null    float64
dtypes: float64(3), int64(1), object(2)
memory usage: 35.9+ KB

In [ ]:
# What function can you use to quickly get an overview of the numeric columns of a Dataframe?
rentals.describe()

            Rooms          Rent  Year_Construction       Space
count  764.000000    764.000000         764.000000  764.000000
mean     2.549738   1768.560942        1983.695026   84.656270
std      1.010826   1118.263961          48.006060   44.195338
min      1.000000    271.250000        1864.000000   14.000000
25%      2.000000   1039.500000        1959.000000   55.097500
50%      2.500000   1565.480000        2015.000000   77.600000
75%      3.000000   2170.000000        2019.000000  104.450000
max      7.000000  14207.000000        2020.000000  413.910000

In [ ]:
# Create a copy of the Dataframe, `rentals_cp`, get the columns of the Dataframe as a list, lowercase each column
# and set the columns of the Dataframe to this new list.
rentals_cp = rentals
rentals_cp.head()

        Region       Condition  Rooms     Rent  Year_Construction   Space
0        Mitte  first_time_use    4.0  2659.00               2019  117.20
1    Kreuzberg  first_time_use    1.0  1200.00               2020   29.33
2     Köpenick       well_kept    2.0   979.00               1997   83.61
3  Wilmersdorf       well_kept    4.0  1830.22               1900  171.18
4    Kreuzberg  first_time_use    2.0  2272.00               2020   88.27

In [ ]:
columns_list= list(rentals_cp.columns)
print(columns_list)

['Region', 'Condition', 'Rooms', 'Rent', 'Year_Construction', 'Space']

In [ ]:
columns_list_lower = [x.lower() for x in columns_list]
print(columns_list_lower)

['region', 'condition', 'rooms', 'rent', 'year_construction', 'space']

In [ ]:
# Create a dictionary of 'old column' -> 'lowercase column' key-values and use
# `rentals.rename` to rename the columns. What's the difference of renaming the columns
# like this compared to the previous way?
columns_dictionary = dict(zip(columns_list, columns_list_lower))
print(columns_dictionary)

{'Region': 'region', 'Condition': 'condition', 'Rooms': 'rooms', 'Rent': 'rent', 'Year_Construction': 'year_construction', 'Space': 'space'}

In [ ]:
rentals_renamed=rentals.rename(columns=columns_dictionary)
rentals_renamed.head()
# What do you know about "in-place" changes in python/pandas? What does it mean, what are the implications?

#In-place changes means irreversible changes in the original object.

        region       condition  rooms     rent  year_construction   space
0        Mitte  first_time_use    4.0  2659.00               2019  117.20
1    Kreuzberg  first_time_use    1.0  1200.00               2020   29.33
2     Köpenick       well_kept    2.0   979.00               1997   83.61
3  Wilmersdorf       well_kept    4.0  1830.22               1900  171.18
4    Kreuzberg  first_time_use    2.0  2272.00               2020   88.27

In [ ]:
# Get the unique 'Region' values from the Dataframe
rentals_renamed['region'].unique()

array(['Mitte', 'Kreuzberg', 'Köpenick', 'Wilmersdorf', 'Charlottenburg',
       'Friedrichsfelde', 'Tiergarten', 'Prenzlauer', 'Wedding',
       'Neukölln'], dtype=object)

# Indexing with `.loc[]`

In [ ]:
# Use `loc` to get the first, third and tenth row in the Dataframe
print(rentals_renamed.loc[[0,2,9]])

       region       condition  rooms    rent  year_construction   space
0       Mitte  first_time_use    4.0  2659.0               2019  117.20
2    Köpenick       well_kept    2.0   979.0               1997   83.61
9  Tiergarten  first_time_use    3.0  1789.0               2020   77.66

In [ ]:
# Use `loc` to get the first, third and tenth row in the Dataframe and only the `Region`, `Rent`, and `Rooms` columns
print(rentals.loc[[0, 2, 9], ['Region', 'Rent', 'Rooms']])

       Region    Rent  Rooms
0       Mitte  2659.0    4.0
2    Köpenick   979.0    2.0
9  Tiergarten  1789.0    3.0

In [ ]:
# Change the order of the rows in the dataframe like this and check the first 10 rows
rentals_shuffled = rentals.sample(frac=1)
rentals_shuffled.head(10)

# Can you get the first, third and tenth row like before or do you need to change sth?

,Region,Condition,Rooms,Rent,Year_Construction,Space
198,Mitte,no_information,2.0,1180.00,2017,56.00
182,Wedding,need_of_renovation,3.0,670.86,1970,76.00
621,Tiergarten,first_time_use,3.0,2031.52,2019,96.97
129,Tiergarten,no_information,1.0,1038.00,2020,30.00
22,Prenzlauer,mint_condition,3.0,1831.00,2019,72.28
263,Tiergarten,well_kept,2.0,1500.00,1999,61.00
190,Tiergarten,no_information,1.0,960.00,1976,43.10
542,Friedrichsfelde,first_time_use,4.0,1535.30,2020,88.29
363,Tiergarten,first_time_use,3.0,2170.00,2019,105.00
397,Wedding,well_kept,1.0,427.00,1956,37.16

In [ ]:
# Create a copy of the Dataframe. Add a prefix of `row_` to each index value
rentals_cp = rentals.copy()
rentals_cp.index = ['row_' + str(x) for x in rentals_cp.index]
rentals_cp.head()

# Get the first, third and tenth rows in the Dataframe and only the `Region`, `Rent`, and `Rooms` columns

selected_rows = rentals_cp.loc[['row_0', 'row_2', 'row_9'], ['Region', 'Rent', 'Rooms']]
print(selected_rows)

           Region    Rent  Rooms
row_0       Mitte  2659.0    4.0
row_2    Köpenick   979.0    2.0
row_9  Tiergarten  1789.0    3.0

# Indexing with `.iloc[]`

In [ ]:
# Get the first 10 rows with `iloc`
rentals.iloc[:10]

            Region       Condition  Rooms     Rent  Year_Construction   Space
0            Mitte  first_time_use    4.0  2659.00               2019  117.20
1        Kreuzberg  first_time_use    1.0  1200.00               2020   29.33
2         Köpenick       well_kept    2.0   979.00               1997   83.61
3      Wilmersdorf       well_kept    4.0  1830.22               1900  171.18
4        Kreuzberg  first_time_use    2.0  2272.00               2020   88.27
5         Köpenick       well_kept    2.0   840.00               1997   73.51
6            Mitte  mint_condition    2.0  1509.45               2015   61.61
7   Charlottenburg       well_kept    2.0   730.73               1900   72.61
8  Friedrichsfelde       well_kept    2.0   561.93               1971   62.40
9       Tiergarten  first_time_use    3.0  1789.00               2020   77.66

In [ ]:
# Get the first row with `iloc`. Try to implement it in a way that the result
# is a Dataframe. ---> possible with double brackets
print(type(rentals.iloc[[0]]))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
print(type(rentals.iloc[0]))

<class 'pandas.core.series.Series'>

In [ ]:
# Get all rows and the 'Region' and 'Rent' columns with `iloc`. Do you notice a difference
# for accessing the columns compared to `loc`?

### to use .loc you have to specify the NAME of the columns  because it is a Label-based function
print(rentals.loc[:,['Region','Rent']])

          Region     Rent
0          Mitte  2659.00
1      Kreuzberg  1200.00
2       Köpenick   979.00
3    Wilmersdorf  1830.22
4      Kreuzberg  2272.00
..           ...      ...
759      Wedding   959.00
760      Wedding   649.00
761  Wilmersdorf  2750.00
762     Köpenick  1259.00
763     Neukölln   888.00

[764 rows x 2 columns]

In [ ]:
### to use .iloc you have to specify the POSITION (column index) of the columns because it is a position-based function
print(rentals.iloc[:,[1,2]])

           Condition  Rooms
0     first_time_use    4.0
1     first_time_use    1.0
2          well_kept    2.0
3          well_kept    4.0
4     first_time_use    2.0
..               ...    ...
759   mint_condition    1.0
760   mint_condition    1.0
761   mint_condition    4.0
762        well_kept    2.0
763  fully_renovated    2.0

[764 rows x 2 columns]

In [ ]:
# What are some differences between accessing a Dataframe with 'loc' vs. 'iloc'?

# Use this example to illustrate the differences a bit.
# Create a new dataframe `rentals_shuffled = rentals.sample(frac=1)`. This is exactly
# the same dataframe. The only difference is that the order of the rows is changed (randomly).
# Look at `rentals` and `rentals_shuffled`. How does the index look? Why is that?
rentals.iloc[[0, 1, 2]]

      Region       Condition  Rooms    Rent  Year_Construction   Space
0      Mitte  first_time_use    4.0  2659.0               2019  117.20
1  Kreuzberg  first_time_use    1.0  1200.0               2020   29.33
2   Köpenick       well_kept    2.0   979.0               1997   83.61

In [ ]:
rentals_shuffled = rentals.sample(frac=1)
#Are the results the same? Why/why not?
print(rentals_shuffled.iloc[[0,1,2]])
type(rentals_shuffled.iloc[[0,1,2]])

          Region        Condition  Rooms    Rent  Year_Construction   Space
395     Neukölln   first_time_use    3.0  2202.0               2019  120.41
763     Neukölln  fully_renovated    2.0   888.0               1990   68.48
421  Wilmersdorf       modernized    1.0   900.0               2015   42.30

pandas.core.frame.DataFrame

# Filtering

In [ ]:
# Explain the differences between `rentals['Rooms']==2` and `rentals[rentals['Rooms']==2]`?
# How can the 2nd expression be split into 2 lines of code?
print(rentals['Rooms']==2) #this returnas a boolean output
print(rentals[rentals['Rooms']==2]) #this returns the actual values from the dataframe

0      False
1      False
2       True
3      False
4       True
       ...
759    False
760    False
761    False
762     True
763     True
Name: Rooms, Length: 764, dtype: bool
             Region        Condition  Rooms     Rent  Year_Construction  Space
2          Köpenick        well_kept    2.0   979.00               1997  83.61
4         Kreuzberg   first_time_use    2.0  2272.00               2020  88.27
5          Köpenick        well_kept    2.0   840.00               1997  73.51
6             Mitte   mint_condition    2.0  1509.45               2015  61.61
7    Charlottenburg        well_kept    2.0   730.73               1900  72.61
..              ...              ...    ...      ...                ...    ...
744      Prenzlauer  fully_renovated    2.0  1366.00               1996  46.00
750         Wedding   no_information    2.0  1079.00               1969  50.79
758        Neukölln       modernized    2.0   693.00               1905  57.00
762        Köpenick        well_kept    2.0  1259.00               2017  91.20
763        Neukölln  fully_renovated    2.0   888.00               1990  68.48

[262 rows x 6 columns]

In [ ]:
# Get all rentals that are in 'well_kept' condition. Use `.loc`. How many rows are there?
print(rentals.loc[rentals['Condition']=='well_kept'])

              Region  Condition  Rooms     Rent  Year_Construction   Space
2           Köpenick  well_kept    2.0   979.00               1997   83.61
3        Wilmersdorf  well_kept    4.0  1830.22               1900  171.18
5           Köpenick  well_kept    2.0   840.00               1997   73.51
7     Charlottenburg  well_kept    2.0   730.73               1900   72.61
8    Friedrichsfelde  well_kept    2.0   561.93               1971   62.40
..               ...        ...    ...      ...                ...     ...
732       Prenzlauer  well_kept    2.0  1489.00               1901   73.41
735            Mitte  well_kept    2.0  1350.00               2014   68.00
736            Mitte  well_kept    3.0  3500.00               2009  165.00
757       Tiergarten  well_kept    4.0  1970.00               1900  127.00
762         Köpenick  well_kept    2.0  1259.00               2017   91.20

[96 rows x 6 columns]

In [ ]:
# Get all rentals in 'Kreuzberg' that are in 'mint_condition'.
# Why do you need round parantheses to make the code work? To fullfill a double condition... the outcome must fullfill this 2 conditions in both fields
print(rentals.loc[(rentals['Region']=='Kreuzberg') & (rentals['Condition']=='mint_condition')])

        Region       Condition  Rooms     Rent  Year_Construction   Space
13   Kreuzberg  mint_condition    2.0  6450.00               2016  186.00
112  Kreuzberg  mint_condition    3.0  3780.00               1904  207.00
137  Kreuzberg  mint_condition    4.0  3295.00               2017  168.86
151  Kreuzberg  mint_condition    3.0  1883.27               2019   98.38
159  Kreuzberg  mint_condition    3.0  1673.95               2019   85.35
186  Kreuzberg  mint_condition    3.0  3000.00               1980   99.00
203  Kreuzberg  mint_condition    3.0  1528.25               2015   84.75
304  Kreuzberg  mint_condition    2.0  1181.30               2019   60.55
312  Kreuzberg  mint_condition    2.0  1040.51               2019   53.03
315  Kreuzberg  mint_condition    2.0  1181.30               2019   60.55
323  Kreuzberg  mint_condition    2.5  2950.00               1920  161.00
326  Kreuzberg  mint_condition    3.0  1817.00               2019   97.62
348  Kreuzberg  mint_condition    3.0  1720.00               2017   74.37
553  Kreuzberg  mint_condition    3.0  2039.00               1900  110.00
601  Kreuzberg  mint_condition    3.0  2150.00               2010   95.80
651  Kreuzberg  mint_condition    3.0  2525.00               1910  170.00
728  Kreuzberg  mint_condition    2.0  1970.00               2019   85.60

In [ ]:
# Get all rentals that were constructed after 2014
print(rentals.loc[rentals['Year_Construction']>2014])

          Region       Condition  Rooms     Rent  Year_Construction   Space
0          Mitte  first_time_use    4.0  2659.00               2019  117.20
1      Kreuzberg  first_time_use    1.0  1200.00               2020   29.33
4      Kreuzberg  first_time_use    2.0  2272.00               2020   88.27
6          Mitte  mint_condition    2.0  1509.45               2015   61.61
9     Tiergarten  first_time_use    3.0  1789.00               2020   77.66
..           ...             ...    ...      ...                ...     ...
756      Wedding  mint_condition    1.0   772.00               2017   20.50
759      Wedding  mint_condition    1.0   959.00               2017   27.80
760      Wedding  mint_condition    1.0   649.00               2017   20.50
761  Wilmersdorf  mint_condition    4.0  2750.00               2017  110.00
762     Köpenick       well_kept    2.0  1259.00               2017   91.20

[397 rows x 6 columns]

# Assignment with `.loc`

In [ ]:
# Create a new column `datasource`. Assign the constant value 'Immoscout' to each row of that column
rentals['datasource']='Immoscout'
rentals.head()

,Region,Condition,Rooms,Rent,Year_Construction,Space,datasource
0,Mitte,first_time_use,4.0,2659.00,2019,117.20,Immoscout
1,Kreuzberg,first_time_use,1.0,1200.00,2020,29.33,Immoscout
2,Köpenick,well_kept,2.0,979.00,1997,83.61,Immoscout
3,Wilmersdorf,well_kept,4.0,1830.22,1900,171.18,Immoscout
4,Kreuzberg,first_time_use,2.0,2272.00,2020,88.27,Immoscout

In [ ]:
# Change the assignment, such that only the first 10 rows have this value, the rest None
rentals.loc[:9,'datasource']='None'
rentals.head(11)

,Region,Condition,Rooms,Rent,Year_Construction,Space,datasource
0,Mitte,first_time_use,4.0,2659.00,2019,117.20,None
1,Kreuzberg,first_time_use,1.0,1200.00,2020,29.33,None
2,Köpenick,well_kept,2.0,979.00,1997,83.61,None
3,Wilmersdorf,well_kept,4.0,1830.22,1900,171.18,None
4,Kreuzberg,first_time_use,2.0,2272.00,2020,88.27,None
5,Köpenick,well_kept,2.0,840.00,1997,73.51,None
6,Mitte,mint_condition,2.0,1509.45,2015,61.61,None
7,Charlottenburg,well_kept,2.0,730.73,1900,72.61,None
8,Friedrichsfelde,well_kept,2.0,561.93,1971,62.40,None
9,Tiergarten,first_time_use,3.0,1789.00,2020,77.66,None
10,Mitte,first_time_use,4.0,2499.00,2019,125.20,Immoscout

In [ ]:
# Change the assignment, such that only rentals from 'Mitte' have this value
rentals.loc[rentals['Region']=='Mitte','datasource']='Mitte'
rentals.head()

,Region,Condition,Rooms,Rent,Year_Construction,Space,datasource
0,Mitte,first_time_use,4.0,2659.00,2019,117.20,Mitte
1,Kreuzberg,first_time_use,1.0,1200.00,2020,29.33,None
2,Köpenick,well_kept,2.0,979.00,1997,83.61,None
3,Wilmersdorf,well_kept,4.0,1830.22,1900,171.18,None
4,Kreuzberg,first_time_use,2.0,2272.00,2020,88.27,None

In [ ]:
# Change the assignmnet, such that only rentals with 2 or more rooms, constructed after 2010 have this assignment
rentals.loc[(rentals['Rooms']>=2) & (rentals['Year_Construction']>2010),'datasource']='2_rooms_after_2010'
rentals.head()

,Region,Condition,Rooms,Rent,Year_Construction,Space,datasource
0,Mitte,first_time_use,4.0,2659.00,2019,117.20,2_rooms_after_2010
1,Kreuzberg,first_time_use,1.0,1200.00,2020,29.33,None
2,Köpenick,well_kept,2.0,979.00,1997,83.61,None
3,Wilmersdorf,well_kept,4.0,1830.22,1900,171.18,None
4,Kreuzberg,first_time_use,2.0,2272.00,2020,88.27,2_rooms_after_2010

In [ ]:
# Add a new column "is_top" which is True if the `Condition` of the aparment is one of 'first_time_use', 'fully_renovated', 'mint_condition', and otherwise False.
rentals['is_top'] = rentals['Condition'].isin(['first_time_use', 'fully_renovated', 'mint_condition'])
rentals.head()

,Region,Condition,Rooms,Rent,Year_Construction,Space,datasource,is_top
0,Mitte,first_time_use,4.0,2659.00,2019,117.20,2_rooms_after_2010,True
1,Kreuzberg,first_time_use,1.0,1200.00,2020,29.33,None,True
2,Köpenick,well_kept,2.0,979.00,1997,83.61,None,False
3,Wilmersdorf,well_kept,4.0,1830.22,1900,171.18,None,False
4,Kreuzberg,first_time_use,2.0,2272.00,2020,88.27,2_rooms_after_2010,True

In [ ]:
# Update the condition to only include apartments in 'Mitte'. Can you think of 2 ways to achieve this result?
rentals.loc[rentals['Region']=='Mitte','Condition']=None
rentals.head()

,Region,Condition,Rooms,Rent,Year_Construction,Space,datasource,is_top
0,Mitte,None,4.0,2659.00,2019,117.20,2_rooms_after_2010,True
1,Kreuzberg,first_time_use,1.0,1200.00,2020,29.33,None,True
2,Köpenick,well_kept,2.0,979.00,1997,83.61,None,False
3,Wilmersdorf,well_kept,4.0,1830.22,1900,171.18,None,False
4,Kreuzberg,first_time_use,2.0,2272.00,2020,88.27,2_rooms_after_2010,True

In [ ]:
# Drop the 'datasource' and 'is_top' columns again
rentals=rentals.drop(columns=['datasource','is_top'])
rentals.head()

        Region       Condition  Rooms     Rent  Year_Construction   Space
0        Mitte            None    4.0  2659.00               2019  117.20
1    Kreuzberg  first_time_use    1.0  1200.00               2020   29.33
2     Köpenick       well_kept    2.0   979.00               1997   83.61
3  Wilmersdorf       well_kept    4.0  1830.22               1900  171.18
4    Kreuzberg  first_time_use    2.0  2272.00               2020   88.27

# Sorting + Grouping

In [ ]:
# Get the top-20 apartments based on the number of rooms
rentals.sort_values(by='Rooms',ascending=False).head(20)

,Region,Condition,Rooms,Rent,Year_Construction,Space
101,Wilmersdorf,first_time_use_after_refurbishment,7.0,4288.00,1900,202.00
675,Wilmersdorf,well_kept,7.0,5876.35,1912,300.00
148,Prenzlauer,mint_condition,6.0,3739.46,1910,237.00
355,Mitte,None,5.0,2310.00,2014,142.00
245,Charlottenburg,no_information,5.0,9774.00,1900,274.00
76,Kreuzberg,first_time_use,5.0,4400.00,1867,236.00
679,Tiergarten,first_time_use,5.0,2851.96,2019,121.36
583,Prenzlauer,mint_condition,5.0,2575.00,2019,150.00
410,Charlottenburg,modernized,5.0,2815.00,1890,175.00
68,Tiergarten,mint_condition,5.0,4945.00,2019,215.00
119,Prenzlauer,mint_condition,5.0,5930.00,2005,324.00
564,Mitte,None,5.0,2865.49,2017,123.08
506,Neukölln,mint_condition,5.0,2295.00,2017,137.31
281,Mitte,None,5.0,6855.48,2005,286.84
53,Charlottenburg,fully_renovated,5.0,3195.00,1905,170.00
369,Tiergarten,well_kept,5.0,2040.00,1908,136.00
636,Charlottenburg,well_kept,5.0,3160.00,1988,169.53
635,Tiergarten,first_time_use,5.0,2851.96,2019,121.36
285,Mitte,None,5.0,4325.69,2015,198.75
536,Wilmersdorf,well_kept,5.0,3104.00,1900,174.63

In [ ]:
# Get the top-20 most expensive and cheapest apartments
rentals.sort_values(by='Rent',ascending=False).head(20)

,Region,Condition,Rooms,Rent,Year_Construction,Space
694,Mitte,None,5.0,14207.00,2015,413.91
245,Charlottenburg,no_information,5.0,9774.00,1900,274.00
281,Mitte,None,5.0,6855.48,2005,286.84
13,Kreuzberg,mint_condition,2.0,6450.00,2016,186.00
653,Mitte,None,2.0,6022.50,2019,123.00
591,Mitte,None,3.0,5936.40,2018,131.92
590,Mitte,None,3.0,5936.40,2018,131.92
119,Prenzlauer,mint_condition,5.0,5930.00,2005,324.00
675,Wilmersdorf,well_kept,7.0,5876.35,1912,300.00
328,Mitte,None,4.0,5774.83,2015,242.64
61,Mitte,None,4.0,5530.00,2016,201.00
646,Mitte,None,3.0,5322.50,2019,123.00
68,Tiergarten,mint_condition,5.0,4945.00,2019,215.00
379,Kreuzberg,fully_renovated,3.0,4875.00,2010,195.00
446,Mitte,None,4.0,4800.00,1894,143.22
560,Tiergarten,fully_renovated,4.0,4800.00,1885,240.00
592,Mitte,None,3.0,4747.60,2018,110.41
594,Mitte,None,3.0,4747.60,2018,110.41
596,Mitte,None,3.0,4747.60,2018,110.41
633,Mitte,None,4.0,4678.30,2015,212.30

In [ ]:
# For the top-20 lists from above, count how many aparments there are per region.
# Sort the output, such that the region with the highest count is on top. Try to
# implement the solutions with `groupby` first and then with `value_counts`.
# What data structure is the result? How does it differ from a Dataframe?
rentals.sort_values(by='Rent',ascending=False).head(20).groupby('Region').count()

                Condition  Rooms  Rent  Year_Construction  Space
Region
Charlottenburg          1      1     1                  1      1
Kreuzberg               2      2     2                  2      2
Mitte                   0     13    13                 13     13
Prenzlauer              1      1     1                  1      1
Tiergarten              2      2     2                  2      2
Wilmersdorf             1      1     1                  1      1

# Grouping

In [ ]:
# Get the average rent over all apartments
rentals['Rent'].mean()

np.float64(1768.560942408377)

In [ ]:
# Get the average rent per region (sort the results) and get the value for region 'Kreuzberg'.
# Turn the output into a Dataframe and the column which represents the average rent should be named 'avg_rent'
rentals.groupby('Region')['Rent'].mean().to_frame().rename(columns={'Rent':'avg_rent'})

                    avg_rent
Region
Charlottenburg   1753.452532
Friedrichsfelde  1043.871731
Kreuzberg        2049.138085
Köpenick         1125.475818
Mitte            2408.725033
Neukölln         1188.114915
Prenzlauer       1996.962264
Tiergarten       1914.824795
Wedding           847.138571
Wilmersdorf      1748.646226

In [ ]:
# Get the average rent grouped by region and condition. Try to use the different ways for doing aggregations as discussed during the class.
# What's the avg. rent for an apartment in 'Mitte' in 'well_kept' condition?
rentals.groupby(['Region','Condition'])['Rent'].mean()

Region          Condition
Charlottenburg  first_time_use                        1437.084444
                first_time_use_after_refurbishment    2062.122857
                fully_renovated                       1925.414000
                mint_condition                        1834.988889
                modernized                            1482.250000
                                                         ...
Wilmersdorf     mint_condition                        1933.666667
                modernized                             900.000000
                no_information                        1523.262500
                refurbished                           1291.333333
                well_kept                             1850.212727
Name: Rent, Length: 70, dtype: float64

In [ ]:
# Do different aggregations per (Region, Condition)
# 1. The average rent
rentals.groupby(['Region','Condition'])['Rent'].mean()

Region          Condition
Charlottenburg  first_time_use                        1437.084444
                first_time_use_after_refurbishment    2062.122857
                fully_renovated                       1925.414000
                mint_condition                        1834.988889
                modernized                            1482.250000
                                                         ...
Wilmersdorf     mint_condition                        1933.666667
                modernized                             900.000000
                no_information                        1523.262500
                refurbished                           1291.333333
                well_kept                             1850.212727
Name: Rent, Length: 70, dtype: float64

In [ ]:
# 2. The most recent construction year
rentals.groupby(['Region','Condition'])['Year_Construction'].max()

Region          Condition
Charlottenburg  first_time_use                        2020
                first_time_use_after_refurbishment    2019
                fully_renovated                       1973
                mint_condition                        2020
                modernized                            1991
                                                      ...
Wilmersdorf     mint_condition                        2019
                modernized                            2015
                no_information                        1995
                refurbished                           1963
                well_kept                             1991
Name: Year_Construction, Length: 70, dtype: int64

In [ ]:
# 3. The biggest apartment by space
rentals.groupby(['Region','Condition'])['Space'].max()

Region          Condition
Charlottenburg  first_time_use                        121.91
                first_time_use_after_refurbishment    160.00
                fully_renovated                       170.00
                mint_condition                        123.00
                modernized                            175.00
                                                       ...
Wilmersdorf     mint_condition                        110.00
                modernized                             42.30
                no_information                         99.63
                refurbished                            77.54
                well_kept                             300.00
Name: Space, Length: 70, dtype: float64

In [ ]:
# 4. The total number of rooms across all apartments
# The result should be a dataframe with 6 columns: 'Region', 'Condition', 'avg_rent', 'newest_year', 'biggest_apt', 'total_rooms'
rentals_grouped = rentals.groupby(['Region', 'Condition']).agg(
    avg_rent=('Rent', 'mean'),
    newest_year=('Year_Construction', 'max'),
    biggest_apt=('Space', 'max'),
    total_rooms=('Rooms', 'sum'))

print(rentals_grouped)

                                                      avg_rent  newest_year  \
Region         Condition
Charlottenburg first_time_use                      1437.084444         2020
               first_time_use_after_refurbishment  2062.122857         2019
               fully_renovated                     1925.414000         1973
               mint_condition                      1834.988889         2020
               modernized                          1482.250000         1991
...                                                        ...          ...
Wilmersdorf    mint_condition                      1933.666667         2019
               modernized                           900.000000         2015
               no_information                      1523.262500         1995
               refurbished                         1291.333333         1963
               well_kept                           1850.212727         1991

                                                   biggest_apt  total_rooms
Region         Condition
Charlottenburg first_time_use                           121.91         52.0
               first_time_use_after_refurbishment       160.00         22.5
               fully_renovated                          170.00         18.0
               mint_condition                           123.00         23.0
               modernized                               175.00         10.0
...                                                        ...          ...
Wilmersdorf    mint_condition                           110.00         17.0
               modernized                                42.30          1.0
               no_information                            99.63         11.0
               refurbished                               77.54          4.0
               well_kept                                300.00         33.5

[70 rows x 4 columns]

# Bonus Questions

In [ ]:
# How many apartments are in Mitte in a 'well-kept' condition?

#first create a data_frame to save the numbers of apartment per condition category
filtered_mitte=rentals.groupby(['Region','Condition']).agg(number_apt=('Region','count'))
print(filtered_mitte)

#the output is a multiindex hierarquical dataset

                                                   number_apt
Region         Condition
Charlottenburg first_time_use                              27
               first_time_use_after_refurbishment           7
               fully_renovated                              5
               mint_condition                               9
               modernized                                   4
...                                                       ...
Wilmersdorf    mint_condition                               6
               modernized                                   1
               no_information                               4
               refurbished                                  3
               well_kept                                   11

[70 rows x 1 columns]

In [ ]:
#second, convert the multiindex hierarquical dataset into a regular dataset and then filter the values that match Mitte and well_kept
# from the Region and Condition columns and then count the number of entries
filtered_mitte_modified=filtered_mitte.reset_index()
filtered_mitte_modified.head()

           Region                           Condition  number_apt
0  Charlottenburg                      first_time_use          27
1  Charlottenburg  first_time_use_after_refurbishment           7
2  Charlottenburg                     fully_renovated           5
3  Charlottenburg                      mint_condition           9
4  Charlottenburg                          modernized           4

In [ ]:
#now filter values
filtered_mitte_modified[(filtered_mitte_modified['Region']=='Mitte') & (filtered_mitte_modified['Condition']=='well_kept')]

##function
filtered = filtered_mitte_modified[
    (filtered_mitte_modified['Region'] == 'Mitte') &
    (filtered_mitte_modified['Condition'] == 'well_kept')
]

if filtered.empty or filtered['number_apt'].values[0] < 1:
    print("There is no well-kept apartments in Mitte")
else:
    print(filtered)

There is no well-kept apartments in Mitte

In [ ]:
# How many apartments are there in Kreuzberg built before 1900?

#funtion
filtered = rentals[
    (rentals['Region'] == 'Kreuzberg') &
    (rentals['Year_Construction'] < 1900)
]

if filtered.empty:
    print("There is no apartment built before 1900 in Kreuzberg")
else:
    print(f"There are {len(filtered)} apartments built before 1900 in Kreuzberg.")
    print(filtered)

There are 3 apartments built before 1900 in Kreuzberg.
        Region                           Condition  Rooms    Rent  \
76   Kreuzberg                      first_time_use    5.0  4400.0
401  Kreuzberg                         refurbished    4.0  2850.0
697  Kreuzberg  first_time_use_after_refurbishment    2.0  1399.0

     Year_Construction  Space
76                1867  236.0
401               1895  127.0
697               1874   50.0

In [ ]:
# What are the average spaces of the apartments by the number of rooms?
average_space_by_rooms = rentals.groupby('Rooms')['Space'].mean()
print(average_space_by_rooms)

Rooms
1.0     34.470748
1.5     41.361111
2.0     65.015725
2.5     90.463125
3.0     99.403167
3.5     98.037500
4.0    130.863333
4.5    106.100000
5.0    194.400526
6.0    237.000000
7.0    251.000000
Name: Space, dtype: float64

In [ ]:
# Which is the most expensive region on average and what is the maximum rent for this region?
average_rent_by_region = rentals.groupby('Region')['Rent'].mean()
print(average_rent_by_region)

#then we order in descending order
average_rent_by_region.sort_values(ascending=False)

def most_expensive_region(rentals):
    # Group by Region and calculate the average rent for each region but index must be reseted because it returns a multiindex hierarchical dataframe
    avg_rent_by_region = rentals.groupby('Region')['Rent'].mean().reset_index()

    # Sort the regions by average rent in descending order
    avg_rent_by_region_sorted = avg_rent_by_region.sort_values(by='Rent', ascending=False)

    # Get the region with the highest average rent (first in the sorted list)
    most_expensive = avg_rent_by_region_sorted.iloc[0]

    # Print the result
    print(f"The most expensive region is {most_expensive['Region']} with an average rent of {most_expensive['Rent']:.2f}.")

# Example usage
most_expensive_region(rentals)

Region
Charlottenburg     1753.452532
Friedrichsfelde    1043.871731
Kreuzberg          2049.138085
Köpenick           1125.475818
Mitte              2408.725033
Neukölln           1188.114915
Prenzlauer         1996.962264
Tiergarten         1914.824795
Wedding             847.138571
Wilmersdorf        1748.646226
Name: Rent, dtype: float64
The most expensive region is Mitte with an average rent of 2408.73.

In [ ]:
# What are the min, max and average number of rooms of the apartments in 'Köpenick'?
filtered_koepenick = rentals[rentals['Region'] == 'Köpenick']
min_rooms = filtered_koepenick['Rooms'].min()
max_rooms = filtered_koepenick['Rooms'].max()
avg_rooms = filtered_koepenick['Rooms'].mean()

############# function
def room_by_region(rentals, region_name):
  #first, the dataframe must befiltered for the specified region
  filtered_region=rentals[rentals['Region']== region_name]

  if filtered_region.empty:
    print(f"No data found for '{region_name}'.")
    return

  min_rooms=filtered_region['Rooms'].min()
  max_rooms=filtered_region['Rooms'].max()
  avg_rooms=filtered_region['Rooms'].mean()

  print(f"The minimum number of rooms in '{region_name}' is '{min_rooms}'.")
  print(f"The maximum number of rooms in '{region_name}' is '{max_rooms}'.")
  print(f"The average number of rooms in '{region_name}' is '{avg_rooms}'.")

###################### Usage
room_by_region(rentals,'Köpenick')

The minimum number of rooms in 'Köpenick' is '1.0'.
The maximum number of rooms in 'Köpenick' is '4.0'.
The average number of rooms in 'Köpenick' is '2.2818181818181817'.

In [ ]:
# Calculate the average rent of each region for new buildings, that means buildings built after 1950.
filtered_new_buildings=rentals[rentals['Year_Construction']>1950]
filtered_new_buildings.head()

      Region       Condition  Rooms    Rent  Year_Construction   Space
0      Mitte            None    4.0  2659.0               2019  117.20
1  Kreuzberg  first_time_use    1.0  1200.0               2020   29.33
2   Köpenick       well_kept    2.0   979.0               1997   83.61
4  Kreuzberg  first_time_use    2.0  2272.0               2020   88.27
5   Köpenick       well_kept    2.0   840.0               1997   73.51

In [ ]:
##### group by region
average_rent_by_region = filtered_new_buildings.groupby('Region')
average_rent_by_region['Rent'].mean().sort_values(ascending=False)

Region
Mitte              2422.319632
Prenzlauer         2298.332400
Kreuzberg          2046.174848
Tiergarten         1988.662662
Wilmersdorf        1579.098333
Charlottenburg     1556.277692
Neukölln           1189.221111
Friedrichsfelde    1051.467255
Köpenick           1048.898409
Wedding             861.239667
Name: Rent, dtype: float64

# Bonus Dataset

In [ ]:
import seaborn as sns

taxis = sns.load_dataset('taxis')
taxis.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
# Create a copy of the Dataframe and increase the 'fare' for any ride where the 'payment' is 'credit card' by 20% using .loc[]
taxis_cp=taxis.copy()
taxis_cp.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
#we create a new column called new_fare in the taxis_cp dataframe populated with the values from the column fare
taxis_cp['new_fare']=taxis_cp['fare']
taxis_cp.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,new_fare
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,7.0
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,5.0
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,7.5
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,27.0
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,9.0

In [ ]:
#now we create a condition where if payment == credit card, the value in fare should be multipled by 1.2 and stored in the respective
#cell of the column new_fare. But we have first to check how the value credit card is represented in the column payment
payment_type= taxis_cp['payment'].unique()
print(payment_type)
type(payment_type)
#get and store the position the position (index) of credit card in the array payment_type that has only on single element, that is, in position [0]
position_cc= np.where(payment_type=='credit card')[0]
print(position_cc) # this is a tuple and the position/index is stored as array[0] and not the actual number 0

#accessing the real position/index value
credit_card_position=payment_type[position_cc[0]]

#now that we now that credit card in in position 0 of the array position_cc, we can filter the dataframe to keep the rows of the taxi_cp of the columns
# payment and new_fare and update the values in the new_fare column
taxis_cp.loc[taxis_cp['payment']== credit_card_position, 'new_fare'] *= 1.2   #here we use loc to selct rows based on a labeled condition which is credit card in colum 'payment'
print(taxis_cp.head())

['credit card' 'cash' nan]
[0]
               pickup             dropoff  passengers  distance  fare   tip  \
0 2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0  2.15
1 2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.00
2 2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5  2.36
3 2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0  6.15
4 2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0  1.10

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West
1    0.0   9.30  yellow         cash  Upper West Side South
2    0.0  14.16  yellow  credit card          Alphabet City
3    0.0  36.95  yellow  credit card              Hudson Sq
4    0.0  13.40  yellow  credit card           Midtown East

            dropoff_zone pickup_borough dropoff_borough  new_fare
0    UN/Turtle Bay South      Manhattan       Manhattan       8.4
1  Upper West Side South      Manhattan       Manhattan       5.0
2           West Village      Manhattan       Manhattan       9.0
3         Yorkville West      Manhattan       Manhattan      32.4
4         Yorkville West      Manhattan       Manhattan      10.8

In [ ]:
taxis_cp.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,new_fare
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,8.4
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,5.0
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,9.0
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,32.4
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,10.8

In [ ]:
# Try and reproduce the following table:

![Untitled.png]()

# Bonus: Local work environment setup

Colab notebooks are great to show code in class, but it's useful to know how to work in a local setup on your machine (that's usually how you'll work at a company). The easiest setup is using Visual Studio Code (VS Code), an open-source [IDE](https://en.wikipedia.org/wiki/Integrated_development_environment) by Microsoft, and its extensions for notebooks and data science packages. If you're interested and have time, try to set up VS Code on your machine, and look into some tutorials for creating notebooks and data science packages. Once you're familiar with it, you can try to do some of the exercises in your notebooks there. If you feel confident, you can continue working with your
local setup throughout the class
* VS Code: https://code.visualstudio.com/
* Data Science in VS Code: https://code.visualstudio.com/docs/datascience/overview
* Working with notebooks in VS Code: https://code.visualstudio.com/docs/datascience/jupyter-notebooks
* Data Science tutorial in VS Code (the parts about machine learning are not so relevant): https://code.visualstudio.com/docs/datascience/data-science-tutorial

**Note**: The following is more about a ubiquitous tool used at software companies. It's not necessary to get too familiar with it when you're starting, but it can be useful if you want to work at a software company or on a software project with multiple people and on the same code.

Github is a platform where all kinds of companies, organizations, people, etc. put and manage their code (there are other similar platforms, such as GitLab, Bitbucket, ... but Github is the most commmon and the principles are the same). If you're interested to find out more, check out their intro tutorial https://github.com/skills/introduction-to-github. If you like you can also check out more tutorials https://skills.github.com/.